### ISSUE TITLE
rotate is broken since 0.2.2

### ISSUE THREAD

**Issue by Eriken** [monostream/tifig#26] opened 2018-02-20 14:19 UTC
Sample image: 
`https://www.jottacloud.com/p/fazermint82/40c6ccc110bd46f69b4cc857702b0c3d`

run:
`tifig -i test.heic -o test.heic.jpeg`

The image is not rotated, the metadata embedded is also incorrect:
```
Eriks-iMac:Downloads erik$ exiftool -j -n test.heic.jpeg 
[{
  "SourceFile": "test.heic.jpeg",
  "ExifToolVersion": 10.78,
  "FileName": "test.heic.jpeg",
  "Directory": ".",
  "FileSize": 3604479,
  "FileModifyDate": "2018:02:20 15:16:36+01:00",
  "FileAccessDate": "2018:02:20 15:16:39+01:00",
  "FileInodeChangeDate": "2018:02:20 15:16:38+01:00",
  "FilePermissions": 644,
  "FileType": "JPEG",
  "FileTypeExtension": "JPG",
  "MIMEType": "image/jpeg",
  "JFIFVersion": "1 1",
  "ExifByteOrder": "MM",
  "Orientation": 1,
  "XResolution": 25.4,
  "YResolution": 25.4,
  "ResolutionUnit": 2,
  "ExifImageWidth": 4032,
  "ExifImageHeight": 3024,
  "ImageWidth": 4032,
  "ImageHeight": 3024,
  "EncodingProcess": 0,
  "BitsPerSample": 8,
  "ColorComponents": 3,
  "YCbCrSubSampling": "2 2",
  "ImageSize": "4032x3024",
  "Megapixels": 12.192768
}]
```
I get the same result with tiff and png.

Regards Erik

**Comment by jtomson** [comment] 2018-02-26 16:00
fwiw I am unable to reproduce this issue with 0.2.2 static. The exif of the test heic and the output jpg are identical

```bash
> tifig --version
tifig 0.2.2
> tifig -i test.heic -o test.heic.jpeg
> exiftool -j -n test.heic.jpeg
[{
  "SourceFile": "test.heic.jpeg",
  "ExifToolVersion": 9.46,
  "FileName": "test.heic.jpeg",
  "Directory": ".",
  "FileSize": 3606227,
  "FileModifyDate": "2018:02:26 15:57:33+00:00",
  "FileAccessDate": "2018:02:26 15:57:34+00:00",
  "FileInodeChangeDate": "2018:02:26 15:57:33+00:00",
  "FilePermissions": 644,
  "FileType": "JPEG",
  "MIMEType": "image/jpeg",
  "JFIFVersion": "1 1",
  "ExifByteOrder": "MM",
  "Make": "Apple",
  "Model": "iPhone 7 Plus",
  "Orientation": 3,
  "XResolution": 72,
  "YResolution": 72,
  "ResolutionUnit": 2,
  "Software": 11.0,
  "ModifyDate": "2017:08:17 14:46:38",
  "YCbCrPositioning": 1,
  "ExposureTime": 0.001692047377,
  "FNumber": 1.8,
  "ExposureProgram": 2,
  "ISO": 20,
  "ExifVersion": "0221",
  "DateTimeOriginal": "2017:08:17 14:46:38",
  "CreateDate": "2017:08:17 14:46:38",
  "ComponentsConfiguration": "1 2 3 0",
  "ShutterSpeedValue": "0.00169199941500991",
  "ApertureValue": 1.79999993941969,
  "BrightnessValue": 8.187375415,
  "ExposureCompensation": 0,
  "MeteringMode": 5,
  "Flash": 16,
  "FocalLength": 3.99,
  "SubjectArea": "2015 1511 2217 1330",
  "RunTimeFlags": 1,
  "RunTimeValue": 373603334166,
  "RunTimeScale": 1000000000,
  "RunTimeEpoch": 0,
  "HDRImageType": 4,
  "SubSecTimeOriginal": 289,
  "SubSecTimeDigitized": 289,
  "FlashpixVersion": "0100",
  "ColorSpace": 65535,
  "ExifImageWidth": 4032,
  "ExifImageHeight": 3024,
  "SensingMethod": 2,
  "SceneType": 1,
  "CustomRendered": 4,
  "ExposureMode": 0,
  "WhiteBalance": 0,
  "FocalLengthIn35mmFormat": 28,
  "SceneCaptureType": 0,
  "GPSLatitudeRef": "N",
  "GPSLongitudeRef": "E",
  "GPSAltitudeRef": 0,
  "GPSTimeStamp": "12:46:37.37",
  "GPSSpeedRef": "K",
  "GPSSpeed": 0.1217441957,
  "GPSImgDirectionRef": "T",
  "GPSImgDirection": 121.7997433,
  "GPSDestBearingRef": "T",
  "GPSDestBearing": 121.7997433,
  "GPSDateStamp": "2017:08:17",
  "ImageWidth": 4032,
  "ImageHeight": 3024,
  "EncodingProcess": 0,
  "BitsPerSample": 8,
  "ColorComponents": 3,
  "YCbCrSubSampling": "2 2",
  "Aperture": 1.8,
  "GPSAltitude": 57.79792746,
  "GPSDateTime": "2017:08:17 12:46:37.37Z",
  "GPSLatitude": 59.8448194444444,
  "GPSLongitude": 10.7815444444444,
  "GPSPosition": "59.8448194444444 10.7815444444444",
  "ImageSize": "4032x3024",
  "RunTimeSincePowerUp": 373.603334166,
  "ScaleFactor35efl": 7.01754385964912,
  "ShutterSpeed": 0.001692047377,
  "SubSecCreateDate": "2017:08:17 14:46:38.289",
  "SubSecDateTimeOriginal": "2017:08:17 14:46:38.289",
  "CircleOfConfusion": "0.00428159213961349",
  "FOV": 65.4705078447874,
  "FocalLength35efl": 28,
  "HyperfocalDistance": 2.06570353074275,
  "LightValue": 13.2249362284532
}]
```

**Comment by monostefan** [comment] 2018-03-16 14:09
I am also not able to reproduce this, neither with current master nor with our latest static release. Are you sure you got the right build? 😛 

I'm closing this issue, feel free to open it again whenever you think the issue is still reproducible.

**Closed by monostefan** 2018-03-16 14:09 UTC

**Comment by brendan-rius** [comment] 2018-03-20 15:33
I have the same problem with current master (7dea067ec7db1215bbccd2cafd1a627857ca4346).

```
$ tifig --version
tifig 0.2.2
$ exiftool -j -n image.heif | grep Orientation
  "Orientation": 6,
$ tifig -v -i image.heif -q 80 -p /hello/output.jpg
Grid is 3088x2320 pixels in tiles 7x5
Export & decode HEVC: 234ms
Saving image: 96ms
Total Time: 344ms
$ exiftool -j -n output.jpg | grep Orientation
  "Orientation": 1,
```

as you can see the orientation metadata has changed, and thus the image is wrongly rotated :(

**Comment by brendan-rius** [comment] 2018-03-20 15:48
Also, I have tried with 0.2.1 and bacj then it was working properly. I feel this might have been broken in commit 08baa177ba8b7099724c1cd325e45a12c90951f6

**Comment by b051** [comment] 2018-09-11 16:13
Hi, I met similar issue with the docker image, tried with monostream/tifig and guetux/tifig, - wrong orientation, no gps.
The mac version is working properly.

**Comment by Eriken** [comment] 2018-09-21 18:36
This might be related:
https://github.com/ImageMagick/ImageMagick/issues/1232
Fix:
https://github.com/ImageMagick/ImageMagick/pull/1233

Either way, I am upgrading to IM 7 so I do not need this trustful cli anymore. 

Thank you for your effort!

Erik
